### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tomlcooper** [tschoffelen/PHP-Passkit#11]
If I leave my $tempPath as '/tmp/' I get an error in my device console saying PassBook Pass download failed: No data supplied. If I change my $tempPath to 'tmp/' I get the error 'Error: Error while creating pass.pkpass. Check your Zip extension.' Please help me, I don't know where it's going wrong!

**Comment by tschoffelen** [comment]
Please check out the [PHP-PKPass](/tschoffelen/PHP-PKPass) library instead for pass creation. The code in this library is slightly outdated.
